tried handling the IPvar validation using regex

diff --git a/0x07-networking_basics/5-is_the_host_on_the_network b/0x07-networking_basics/5-is_the_host_on_the_network
--- a/0x07-networking_basics/5-is_the_host_on_the_network
+++ b/0x07-networking_basics/5-is_the_host_on_the_network
@@ -2,12 +2,20 @@
 #script pings an IP address passed as an argument
 #IPvar variable
 
-IPvar="${1}"
-
-#fileame variable
-fileName=$(basename "${BASH_SOURCE[@]}")
-if [ -z "${IPvar}" ]; then
-	echo "usage: ${fileName} {IP_ADDRESS}"
-else
-	ping -c 5 "${IPvar}"
+# Check if argument is provided
+if [ "$#" -ne 1 ]; then
+	    # Display usage message if no argument is provided
+	        echo "Usage: $(basename "$0") {IP_ADDRESS}"
+		    exit 1
 fi
+
+IPvar="$1"
+
+# Validate the format of the IP address using a regex
+if ! [[ "$IPvar" =~ ^([0-9]{1,3}\.){3}[0-9]{1,3}$ ]]; then
+	    echo "Invalid IP address format: $IPvar"
+	        exit 1
+fi
+
+# Ping the specified IP address
+ping -c 5 "$IPvar"
